### ISSUE TITLE
Botnet problem?

### ISSUE THREAD

**Issue by MoneroCrusher** [bschn2/rainforest#2]
Hi Bill,

Very interesting algo & presentation.
The big problem I see with routers & mobile phones being economically as viable to mine with as high-end CPUs/GPUs would be the likely increased botnet incentive/stealing of power&recources.

Is there a way to make this for GPUs only? Or perfectly balanced between CPU & GPUs but letting GPUs mine more because of parallelism while also making ASICs too complex?

Reasoning: GPU farms are better protected than your average mobile phone or router, therefore decreasing risk of botnets and/or 51% attacks.

Question:
How is it possible that a RK3368 does 50% of the hashrate of a RX 560, while consuming 1/20 of the energy? Would it be possible to bring GPU wattage down (ignoring the rest of the PC) to a similar level?
Otherwise this will just create a huge shift from GPU farms to RK3368, Raspberry Pi & Huawei farms

**Comment by bschn2** [comment]
Hello Sir!

Please excuse my late response, I don't connect often to github and I didn't notice your comment.

Well, I have a different point of view on your concern. Vulnerable machines will always be used as botnets for various activities, whether it is network attacks or crypto-currency mining doesn't make much difference, except that the latter is less damaging to the internet in general. Also, by encouraging everyone to mine (possibly as a way to pay less for their internet subscription), I predict that any drop of income caused by a squatted CPU will trigger quick action from the user and will lead to the device being fixed. Right now people don't care about their devices being used to attack other sites.

Also, I'm really against making something GPU only. GPUs are elitist. I had to buy a graphics card to implement and measure the rainforest performance because nobody among my numerous relatives had a usable one. I think that there are much less than 1 GPU for 10 CPUs. This explains why many people still think that mining is illegal. It's reserved to those using dedicated hardware for this. My goal is to ensure that everyone can easily mine so that we can multiply by 10 or 100 the number of miners. This is the only way to reduce the importance of professional miners. Please note that I took a great care in this algorithm design to ensure that GPUs are not defavored in order to protect existing investments. It's just that for the same investment you'd rather buy CPUs which consume less power now.

Regarding the fact that the Geekbox does 50% of the hashrate of the RX560, it's explained in the presentation, but it also surprised some attendees at the conference. The reason is simple : GPUs are made of high density very specialized computation units, just like CPUs are made of very specialized units. None of them is very good at doing the other one's job. The algorithm was highly optimized to make intensive use of a CPU's highly optimized integer units and L1 cache unit. The equivalent ones in a GPU are not efficient at this workload at all.

You couldn't realistically bring the GPU wattage down enough because GPUs are designed for optimal performance at the cost of wasting resources. Todays CPUs are designed to spend a lot of time idling and to optimize their idle time. But even a decade ago, idle CPUs used to consume more. I remember my old Core2 duo drawing a lot of power in idle. To make it simple, the power draw on an IC comes from the square of the current multiplied by wire resistance. The current is proportional to the frequency and the wire+gate capacitance. This capacitance depends on the silicon technology used. The high parallelism of GPUs causes the total current to be extremely high, despite their low frequency. Current CPUs power-gate (disconnect) unused units to save time. This wouldn't be practical on highly parallel GPUs.

I really hope we can see a progressive shift from GPU farms to much lower power devices. If for the same mining performance we can divide the total power drawn by only 10, it will already by fantastic. And it seems there are even more efficient devices than Raspberry Pi as indicated in this recent test report where one comment mentions a similarly priced device achieving almost 3 times the board's performance  :  https://www.linkedin.com/pulse/more-efficient-mining-raspberry-pi-julien-delorme/

Another important point I'm seeing is the entry cost to start mining. Right now building a new machine with a GPU roughly costs $500. Just to start mining. Not everyone can spend $500 just hoping to make the right choice and to keep this hardware usable for 2-3 years to cover its cost. And you can't do with less because it will simply not bring you anything. With only $35 you can buy a Raspberry Pi so you can start with investing much lower if it becomes possible to mine with such inexpensive hardware. This further reduces the elitist aspect of mining and opens it to a wider participation and thus pushes the 51% attack risk even further.

I hope I could convince you of the importance of giving a maximum number of people an easy and inexpensive access to crypto-mining so that we can heal the crypto-currency ecosystem which currently is as bad as banks with most of the control in the hands of very few big companies.

**Comment by ClashLuke** [comment]
You may be interested in this post by hyc, one of the most trusted developers in this scene, who basically shuts down your entire post with one sentence.
https://github.com/monero-project/monero/issues/5085#issuecomment-455828981

**Comment by bschn2** [comment]
This is absolutely true when energy is used the same way by all players. When energy is not used similarly (i.e. some waste it in not well suited devices, others optimize it in well suited devices), then some have more power than others for the same amount of energy. And today devices wasting energy are not much more expensive than those using it appropriately. So once everyone starts to focus on energy-efficient devices, then the acquisition cost (i.e. investment) starts to play a role and even the small players have a chance to participate because they are not condemned to use extremely unfair devices. What is true however is that the protection is brought by the total amount of energy available for the task.

I'm closing this issue which is more about a philosophical debate than a technical issue in the code :-)
