### ISSUE TITLE
__builtin_clrsbl unknown in msvc

### ISSUE THREAD

**Issue by djm34** [bschn2/rainforest#21]
Hello, 
I am currently trying to implement the code in cuda when I ended on some problem regarding __builtin_clrsbl (or builtin_clz) for the verification code running on cpu. 

On a similar matter there is a "__asm__ volatile" which isn't recognize by msvc and which didn't have a non asm alternative (found one in the opencl code though), but it would be better to make sure the code runs on every operating system

**Comment by bschn2** [comment]
Hello Sir,

I too would like to be sure it runs on every relevant operating system. Since I moved to Ubuntu two years ago, I don't have access to a Windows development machine anymore and I don't have access to MSVC to test the code, so I'm taking your feedback with great consideration.

I have now made sure __builtin_clrsbl() is defined also on non-gcc platforms and implemented a definition of the __builtin_clrzl() it relies on. Let me know how it works.

Regarding the other asm volatile, I spotted it, it was an optimization in the divbox which is only relevant where the div and mod can be separate instructions (arm for example), and I have now enclosed it between the suitable ifdef conditions.

Thank you Sir!

**Comment by djm34** [comment]
I am trying the new version of __buiktin_clrsbl. 
Thinking about it, I am a little confused with the condition if ( x < 0) while x in an unsigned long long...
regarding the clzll function, it seems to give a different value compared to the builtin cuda version

**Comment by bschn2** [comment]
Hello Sir,
sorry I missed this one, we should probably close issues more often. The test on x<0 is performed on signed value, and is here to test the topmost bit, exactly like clrsbl does. What this builtin (and the equivalent ARM instruction) does is to count the number of sign bits. If the number is positive, its highest bit is cleared and the instruction counts the number of following bits equal to zero. If the number is negative, its highest bit is set and the instruction counts the number of following bits equal to 1. This is why there is this test to decide whether we count ones or zeroes.

I'm closing it now to avoid missing new issues, feel free to open a new one in case of problem.
