### ISSUE TITLE
loops parameter (sin_scaled) returning 1 or even 0 (one instance)

### ISSUE THREAD

**Issue by djm34** [bschn2/rainforest#33]
Hello, 
I am currently running on the testnet pool and noticed several case where the pool was rejecting the share I was submitting even though it was validated on cpu. 

Looking in the parameters I gather during testing I see that most of them are rejected when loops=1 and in one case loops = 0 

here an example for loops = 1 (msgh = 0x83621d5d loops = 1)
and loops = 0 (msgh = 0x858947af loops = 0). 

Do I need to reject these solution ? (I was checking into the code I didn't see anything about it)
Obviously loops = 0 should be rejected but what about loops = 1 ?

**Comment by bschn2** [comment]
Hello Sir!
well, at first glance it is not possible:

```
static unsigned int sin_scaled(unsigned int x)
{
	int i;

	i = ((x * 42722829) >> 24) - 128;
// i = -128 to +127
	x = 15 * i * i * abs(i);  // 0 to 15<<21
// x=0 to 15*128*128*128=31457280
	x = (x + (x >> 4)) >> 17;
// x=0 to 255
	return 257 - x;
// return 2 to 257
}
```

Oh, maybe I know what is happening. Is your code this one ? https://github.com/MicroBitcoinOrg/CudaMiner/blob/rfv2/rainforest/cuda-rainforest2.cu

If so, you need to change your sin_scaled function's prototype to return an unsigned int, not a uchar:
```
__device__ static uchar sin_scaled(uint x)
```
Otherwise 2..257 will respectively be mapped to 2..255 then 0 for 256, then 1 for 257. This definitely explains your invalid shares.

**Comment by djm34** [comment]
oh, ok. Good catch. :D
